### PR TITLE
Add Makefile

### PR DESCRIPTION
**Pull request by HideakiImamura**
I added
- `make build`: build using hugo
- `make start`: start the server
- `make clean`: clean up the build

### CODE REVIEW

**Comment by HideakiImamura** [comment]
@not522 Could you review this PR after #18?

**Comment by HideakiImamura** [comment]
This PR is not ready for review.

**Comment by HideakiImamura** [comment]
@y0z Could you review this PR?

**Review by y0z — APPROVED** [review]
LGTM

**Pull request merged**
