### PR TITLE
Do not run the scheduled CI on the fork

### PR DESCRIPTION
**Pull request by HideakiImamura**
## Motivation

The CI frequently fails in the fork. We should not run the scheduled CI on the fork.

## Description of the changes

Do not run the scheduled CI on the fork

### CODE REVIEW

**Comment by y0z** [comment]
After changing the settings, the build CI for this pull request doesn't work as expected and it says "Waiting for status to be reported."

image

**Review by y0z — COMMENTED** [review]
I leave a comment.

**Comment by HideakiImamura** [comment]
@y0z Fixed for the error. PTAL.

**Review by y0z — APPROVED** [review]
LGTM

**Pull request merged**
